name: Build and Publish

on:
  release:
    types: [ "created" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Replace version in package.json to be semver compatible
        run: sed -i "s/0.0.0/$(echo $GITHUB_REF | sed 's/refs\/tags\///')/" package.json

      - name: Build
        run: pnpm build

      - name: Publish package on NPM
        run: pnpm publish . --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}

      - name: Publish Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: docs
